module.exports = {
    astar: './src/pages/astar.ts',
    webgpu: './src/pages/webgpu.ts',
    jungle: './src/pages/jungle.ts',
    avatar: './src/pages/avatar.ts',
    astar3d: './src/pages/astar3d.ts',
    table: './src/pages/table/main.ts',
    earth: './src/pages/earth/main.ts',
    clock: './src/pages/clock/main.ts',
    effect: './src/pages/effect/main.ts',
    nexus: './src/pages/nexus/main.ts',
    cacheAsync: './src/pages/cacheAsync.ts',
    webgpuSort: './src/pages/webgpuSort.ts',
    webgpuMatrix: './src/pages/webgpuMatrix.ts',
    '3dloading': './src/pages/3dloading/main.ts',
    sensor: './src/pages/neural/sensor.ts',
};
